from snakemake.utils import min_version

min_version("7.3.6")



### workflow.basedir for the location of the Snakefile
configfile: os.path.join(workflow.basedir, "..", "config/config.yaml")


report: "report/workflow.rst"


# print(os.getcwd())


# Using singularity for conda/mamba support
# container: "docker://condaforge/mambaforge"

include: "rules/common.smk"
include: "rules/pedigree.smk"
include: "rules/ref.smk"

if config["fastq_input"]["enable"]:
    include: "rules/premap.smk"
    include: "rules/mapping.smk"
else:
    include: "rules/bam_input.smk"

include: "rules/bam_qc.smk"
include: "rules/gatk_hc.smk"
include: "rules/deepvariant.smk"
include: "rules/call_dnm.smk"
include: "rules/jigv.smk"
include: "rules/phasing.smk"
include: "rules/dnSTR.smk"

if config["dnSV"]["enable"]:
    include: "rules/dnSV.smk"

if config["multiqc"]["enable"]:
    include: "rules/multiqc.smk"

rule all: 
    input: 
        output_dir + "/dnm_vcf_summary/DNM_summary.txt",
        expand(output_dir + "/call_JIGV/{fam}.JIGV.html", fam=fam_ids),
        expand(output_dir + "/phase_DNMs/{fam}.parental_origin.tab", fam=fam_ids),
        optional_output=optional_output,
        
        


