name: TriosCompassV2
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - snakemake==7.3.7
  - pip==22.3.1
  - python==3.10.6
  # https://github.com/snakemake/snakemake/issues/1899
  - tabulate==0.8.10 
  - pip:
    - eido==0.1.9
    - peds==1.3.2
    - peppy==0.35.4
    