pep_version: 2.0.0
sample_table: sample_fastq.csv

# In manifest file, Sample_ID + Flowcell should be unique
sample_modifiers:
  append:
    sample_name: "sn"
  derive:
    attributes: [sample_name]
    sources:
      sn: "{SAMPLE_ID}_{FLOWCELL}_L{LANE}"
