name: fastq_test

pepfile: "config/fastq_pep.yaml"
pepschema: "../schemas/fastq_schema.yaml"

output_dir: "output"

ref:
  sequence: "ref/Homo_sapiens_assembly38.fasta"
  build: "hg38"

ped_dir: "new_cgr_pedfiles"

parabricks:
  singularity_cmd: " /usr/local/current/singularity/4.0.3/bin/singularity exec --pwd /mnt --nv -B `pwd`:/mnt docker://nvcr.io/nvidia/clara/clara-parabricks:4.0.0-1 "

fastq_input:
  enable: True # process the fastq input; False if bam inputs are provided
  fastqc: 
    enable: True
  fastq_screen:
    enable: True
    config: "ref/fastq_screen.abs.conf"

bam_input:
  reset_RG: True

bam_qc:
  flagstat: 
    enable: True
  collectwgsmetrics:
    enable: True
  collectmultiplemetrics:
    enable: True

deepvariant:
  # DeepVariantWGS 
  glnexus_config: "DeepVariant_unfiltered"

call_dnm:
  interval: "ref/hg38.wgs_interval.bed"
  dv:
    min_gq: 3
    min_dp: 20
  hc:
    min_gq: 20
    min_dp: 30

threads:
  bwa_index: 16
  fastp: 8
  fastq_screen: 8
  fq2bam: 48
  flagstat: 16
  collectmultiplemetrics: 32
  gatkhc_pb: 24
  gatk_combine_gvcf: 16
  gatk_cgp: 16
  gatk_genotype_gvcf_pb: 16
  deepvariant_pb: 48
  glnexus_dv: 8
  replace_rg: 8

### for pedigree files
ped_dir: "ped"

### Settings for dnSTR calling
split_total: 400
gangstr_panel: "STR/hg38_ver13.le9.bed"
hipstr_panel: "STR/hg38_ver13.hipstr_9.bed"
hipstr_filters: " --min-span-coverage 3 --min-supp-reads 3 "
gangstr_filters: " --max-perc-encl-parent 0.05 --min-encl-match 0.9 --min-total-encl 10 --gangstr "
dup_reg: "STR/GRCh38GenomicSuperDup.bed.gz" # come with GRCh38GenomicSuperDup.bed.gz.tbi 

### WhatsHap
phase_window: 10000



