name: GIAB_40X

pepfile: "../input/40X_pep.yaml" # relative to ./TriosCompass_v2
pepschema: "../schemas/bam_schema.yaml" # relative to ./TriosCompass_v2/rules/premap.smk

output_dir: "output_40X"


ref:
  sequence: "ref/Homo_sapiens_assembly38.fasta"
  build: "hg38"

ped_dir: "input/ped"

parabricks:
  singularity_cmd: " singularity exec --pwd /mnt --nv -B `pwd`:/mnt -B /vf,/spin1,/data,/fdb,/gpfs,/lscratch docker://nvcr.io/nvidia/clara/clara-parabricks:4.0.0-1 "

fastq_input:
  enable: False # process the fastq input; False if bam inputs are provided
  fastqc: 
    enable: True
  # fastq_screen:
  #   enable: True
  #   config: "ref/fastq_screen.abs.conf"

bam_input:
  reset_RG: False

bam_qc:
  flagstat: 
    enable: True
  collectwgsmetrics:
    enable: True
  collectmultiplemetrics:
    enable: True

deepvariant:
  # DeepVariantWGS 
  glnexus_config: "DeepVariant_unfiltered"

gatk_hc: 
  gatk_hard_filter: 
    enable: True
    filter: "QD>=2 & FS<=60 & SOR<4 & MQ>38 & MQRankSum>= -12.5 & ReadPosRankSum >= -8"
    # filter: "QD>=2 & FS<=60 & SOR<=3 & MQ>=40 & MQRankSum>= -12.5 & ReadPosRankSum >= -8"
    
call_dnm:
  interval: "ref/hg38.wgs_interval.bed"
  max_err: 0.02 # max AF for parenets (AD[1]/AD) 
  AB: 0.25 # allele balance is btwn (AB, 1-AB)
  dv:
    min_00_gq: 20
    min_01_gq: 15 # 3 for high depth
    min_dp: 15
    max_dp: 125
    min_PL: 20
  hc:
    min_00_gq: 20
    min_01_gq: 20
    min_dp: 15
    max_dp: 125
    min_PL: 20

phasing:
  enable: True
  window_size: 10000
  # the perl script path relative to the working directory
  perl_cmd: "perl TriosCompass_v2/workflow/scripts/extract_parental_origin.pl "

JIGV: 
  enable: True

dnSTR:
  # split bed into chunks to speed up dnSTR call
  enable: True
  split_n: 400
  dup_reg: "ref/STR/GRCh38GenomicSuperDup.bed.gz" # come with GRCh38GenomicSuperDup.bed.gz.tbi 
  hipstr:
    enable: True
    ref_panel: "ref/STR/hg38_ver13.hipstr_9.bed"
    monstr_filter: " --min-span-coverage 3 --min-supp-reads 3 "
    dumpstr_call_args: >
            --hipstr-min-call-DP 15  
            --hipstr-max-call-DP 1000 
            --hipstr-min-call-Q 0.9 --drop-filtered 
            --vcftype hipstr --hipstr-min-supp-reads 1 
            --hipstr-max-call-flank-indel 0.15 
            --hipstr-max-call-stutter 0.15 

multiqc:
  enable: True
  output_dir: "MultiQC__40X_output"
  
dnSV:
  enable: True
  GraphTyper2+smoove:
    enable: True
    exclude_bed: "ref/exclude.cnvnator_100bp.GRCh38.20170403.bed"
  Manta:
    enable: True
  

threads:
  bwa_index: 16
  fastp: 8
  fastq_screen: 8
  fq2bam: 48
  flagstat: 16
  collectwgsmetrics: 16
  collectmultiplemetrics: 32
  gatkhc_pb: 24
  gatk_combine_gvcf: 16
  gatk_cgp: 16
  gatk_genotype_gvcf_pb: 16
  deepvariant_pb: 48
  glnexus_dv: 8
  phase_child: 2
  phase_trios: 2
  replace_rg: 4
  manta_call: 10
  uniq_svid: 4
  svimmer: 4
  graphtyper: 40
  smoove: 20

  





