name: giab_trios_benchmark

pep_version: 2.0.0
sample_table: giab_manifest2.csv
output_dir: "giab_output"
input_bam_dir: "bam"
input_fq_dir: "/vf/users/DCEG_Chernobyl/NP0436-HE5/GIAB_DATA"
hg38_ref: "ref/Homo_sapiens_assembly38.fasta"

sample_modifiers:
  append:
    sample_name: "sn"
    bam_name: "bam"
  derive:
    attributes: [sample_name, bam_name]
    sources:
      sn: "{FLOWCELL}_{SAMPLEID}_{INDEX}_L{LANE}"
      bam: "{SAMPLEID}_{INDEX}_L{LANE}"

